### ISSUE TITLE
build stuck at 0.2.1

### ISSUE THREAD

**Issue by codyduval** [mhanberg/gigalixir-action#10]
Heyo! It looks like the files in the `dist` directory are behind a version - maybe someone forgot to run `ncc build` before they committed and bumped the package to 0.3.0?

Thanks for all your work in the Elixir ecosystem, it is much appreciated! 🙇

**Comment by mhanberg** [comment]
Whoops, that looks like what happened. Sorry about that! I'll get that fixed.

Still getting used to committing build artifacts 😅.

**Comment by mhanberg** [comment]
Should be fixed now!
