### ISSUE TITLE
Migration error : duplicate_table

### ISSUE THREAD

**Issue by ddaugher** [mhanberg/gigalixir-action#11]
I have been using v0.1.0 for a couple months... working fine, started getting following error during 'migration'... updated to v0.3.0 and receive the same error... thoughts?

-----

Running migrations
  /usr/local/bin/gigalixir ps:migrate -a ***
  Pseudo-terminal will not be allocated because stdin is not a terminal.
  Warning: Permanently added '[us-east-1.aws.ssh.gigalixir.com]:31789,[52.73.201.137]:31789' (ECDSA) to the list of known hosts.
  21:57:33.995 [info] == Running 20200429160003 Backoffice.Repo.Migrations.CreateEmployeeTable.change/0 forward
  21:57:33.996 [info] create table employees
  ▸  Given the following expression: Ecto.Migrator.run(List.first(Application.get_env(:***, :ecto_repos)), Application.app_dir(:***, "priv/repo/migrations"), :up, all: true)
  ▸  The remote call failed with:
  ▸  ** (exit) %Postgrex.Error{connection_id: 19266, message: nil, postgres: %{code: :duplicate_table, file: "heap.c", line: "1066", message: "relation \"employees\" already exists", pg_code: "42P07", routine: "heap_create_with_catalog", severity: "ERROR"}, query: nil}
  ▸      (ecto_sql 3.4.2) lib/ecto/adapters/sql.ex:612: Ecto.Adapters.SQL.raise_sql_call_error/1
  ▸      (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
  ▸      (ecto_sql 3.4.2) lib/ecto/adapters/sql.ex:705: Ecto.Adapters.SQL.execute_ddl/4
  ▸      (ecto_sql 3.4.2) lib/ecto/migration/runner.ex:343: Ecto.Migration.Runner.log_and_execute_ddl/3
  ▸      (ecto_sql 3.4.2) lib/ecto/migration/runner.ex:117: anonymous fn/6 in Ecto.Migration.Runner.flush/0
  ▸      (elixir 1.10.3) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
  ▸      (ecto_sql 3.4.2) lib/ecto/migration/runner.ex:116: Ecto.Migration.Runner.flush/0
  ▸      (stdlib 3.11.2) timer.erl:166: :timer.tc/1
  Command '[u'ssh', u'-t', u'root@us-east-1.aws.ssh.gigalixir.com', u'-p', u'31789', u'gigalixir_run', u'migrate']' returned non-zero exit status 1

**Comment by mhanberg** [comment]
Hi,

Can you confirm if that table exists in your database?

If it does, then that’s the reason. you might confirm that the deployed migrations table and your local migrations table are the same. 

-Mitch

**Comment by ddaugher** [comment]
I have resolved this this... it appears that Gigalixir failed in the middle and part of the tables were dropped, but not all... the migrations table was out of sync. I manually reset the database and then the ps:migrate functioned properly.  Thank you for the response.

**Comment by ddaugher** [comment]
I am experiencing another error... the 'Getting current replicas' check is returning the proper data (same as when I run 'gigalixir ps -a <app_name>' from the command line), but the github action never stops polling... I eventually kill the github action manually in order to stop the polling.  thoughts?

**Comment by mhanberg** [comment]
Please close this issue and open another with this different issue.

**Comment by ddaugher** [comment]
will do.
