### ISSUE TITLE
Getting current replicas

### ISSUE THREAD

**Issue by ddaugher** [mhanberg/gigalixir-action#12]
the 'Getting current replicas' check is returning the proper data (same as when I run 'gigalixir ps -a <app_name>' from the command line), but the github action never stops polling... I eventually kill the github action manually in order to stop the polling. thoughts?

here is what the output in the console looks like...
 Run mhanberg/gigalixir-action@v0.3.0
  
Getting current replicas
Waiting 64 seconds...
Getting current replicas
Waiting 128 seconds...
Getting current replicas
Waiting 256 seconds...
Getting current replicas
  /usr/local/bin/gigalixir ps -a backoffice
  {
    "cloud": "aws", 
    "pods": [
      {
        "lastState": {}, 
        "name": "backoffice-db6dcf486-xxxxxx", 
        "sha": "fb33ebad8a362a2e0a74a4exxxxxxx", 
        "status": "Healthy", 
        "version": "86"
      }
    ], 
    "region": "us-east-1", 
    "replicas_desired": 1, 
    "replicas_running": 1, 
    "size": 0.3, 
    "stack": "gigalixir-18", 
    "unique_name": "backoffice"
  }
  
Waiting 512 seconds...

**Comment by mhanberg** [comment]
This is not the reason for the failure, but the polling timing should probably switch to every ten seconds instead of being fancy. 

There's a chance the gigalixir api has changed. I'll take a look when I get a chance.

**Comment by bliitzkrieg** [comment]
I'm also having this issue. @ddaugher did you find a fix?
