### ISSUE TITLE
Would be nice if SSH_PRIVATE_KEY was not required if you don't use Ecto

### ISSUE THREAD

**Issue by henrik** [mhanberg/gigalixir-action#30]
I'm deploying a Phoenix project that doesn't use Ecto (or a DB at all), so having to generate and configure a SSH key seems unnecessary.

Perhaps the setting could be not-required, doced as required if migrations are true, and could raise a helpful error if missing when needed?

**Comment by raulpe7eira** [comment]
I adds this feature in #35 .
