### ISSUE TITLE
Migration failed (too_many_connections)

### ISSUE THREAD

**Issue by drselump14** [mhanberg/gigalixir-action#42]
Enabled the migration and set the correct SSH Private Key.
However, it raises this error when performing a migration

```
 [error] Postgrex.Protocol (#PID<0.305.0>) failed to connect: ** (Postgrex.Error) FATAL 53300 (too_many_connections) too many connections for role
```
Anyone has an idea to fix it?

Any help would be appreciated

**Comment by mhanberg** [comment]
I'll start by saying this doesn't sound like an issue with this project. You should probably ask this on the elixirforum or gigalixir support.

but, it sounds like you're POOL_SIZE is probably set too high when running your migrations, as your application is already running.

So, if you're postgres instance allocates you 20 connections in total, you can't have your app running with a POOL_SIZE of 18, and then run your migrations with a POOL_SIZE of 18. That would be 36 connections, which would probably cause this error.
