### ISSUE TITLE
How to deploy a specific branch to Gigalixir?

### ISSUE THREAD

**Issue by anildigital** [mhanberg/gigalixir-action#5]
We are using the `dev` branch as our main branch and I want to deploy `dev` branch to Gigalixir. From command line I can do it as ```git push gigalixir dev:master```, but how to do that from this action?

**Comment by mhanberg** [comment]
As of now that isn’t possible. 

I’ll see what I can do within the next couple days. There might be a way to do it without adding another configuration options.

**Comment by anildigital** [comment]
@mhanberg Shouldn't this code be able to deploy the current checked out branch HEAD (lets say `dev`) to Gigalixir master? https://github.com/mhanberg/gigalixir-action/blob/master/dist/index.js#L1044

**Comment by mhanberg** [comment]
Not sure, I'll check it out. 

The `HEAD:refs/heads/master` was ripped from a code snippet gist I found from jesseshieh (founder of Gigalixir).

**Comment by mhanberg** [comment]
Hi, turns out you can do this with the latest version as is. You can see the log [here](https://github.com/mhanberg/pipsqueak/runs/578538309?check_suite_focus=true).

All you need to do is change the branch you checkout and the ref you use in the if conditional in the deploy job.

```diff
  deploy:
    needs: verify
-   if: github.ref == 'refs/heads/master'
+   if: github.ref == 'refs/heads/another-branch'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
-         ref: master
+         ref: another-branch
          fetch-depth: 0

      - uses: mhanberg/gigalixir-action@v0.2.1
        with:
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          GIGALIXIR_APP: pipsqueak
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
```

**Comment by anildigital** [comment]
@mhanberg Really thanks. I could deploy it successfully.
