### ISSUE TITLE
GitHub Action stuck at `Getting current replicas`

### ISSUE THREAD

**Issue by anildigital** [mhanberg/gigalixir-action#6]
GitHub Action is stuck at `Getting current replicas`

<img width="960" alt="image" src="https://user-images.githubusercontent.com/266/79039548-89620200-7bff-11ea-903a-b9a6876cbd77.png">

**Comment by mhanberg** [comment]
How many replicas are you configured to have?

**Comment by anildigital** [comment]
@mhanberg Closing this ticket. I didn't set DATABASE credentials in my prod.exs properly so I was getting this error. Error was misleading. I checked `gigalixir logs` and then fixed this.
