### ISSUE TITLE
Only add key & wait for deploy if a migration is running

### ISSUE THREAD

**Issue by mikehostetler** [mhanberg/gigalixir-action#8]
We've got `MIGRATIONS: false` set and our Github action still waits for the deploy to be successful, wasting a few extra minutes every deploy of our Github Action's quota.

Wouldn't it make more sense to move these two lines into the if statement and only run them if you plan to run migrations?

```
await core.group("Adding private key to gigalixir", async () => {
      await exec.exec(path.join(__dirname, "../bin/add-private-key"), [sshPrivateKey]);
    });

    await core.group("Waiting for new release to deploy", async () => {
      await waitForNewRelease(currentRelease, gigalixirApp, 1);
    });
```

**Comment by mhanberg** [comment]
Hi

Thanks for opening this issue. I’ll be able to look into this on Tuesday. 

In the mean time, feel free to submit a PR if you have the free time. 

Thanks!!
